# For full config options, check the docs:
#    docs.serverless.com

service: summit-lucky-draw

custom:
  client:
    bucketName: origin.summit18.awsug.tw
  conf: # Match those in mail templates as well
    domain: summit18.awsug.tw
    sender: no-reply@awsug.tw
    verifierArn: arn:aws:iam::406053587786:role/verifierSummit18

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
  environment:
    hello: world
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sts:AssumeRole"
      Resource: ${self:custom.conf.verifierArn}

plugins:
  - serverless-finch

functions:
  register:
    handler: handler.register
    events:
     - http:
         path: api/register
         method: post
  verify:
    handler: handler.verify
    events:
     - http:
         path: api/verify
         method: get

resources:
  Resources:
    MasterKey:
      Type: AWS::KMS::Key
      Properties:
        KeyPolicy:
          Version: '2012-10-17'
          Id: 'key-default-1'
          Statement:
            - Sid: 'well well well'
              Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - ':'
                    - - 'arn:aws:iam:'
                      - Ref: AWS::AccountId
                      - 'root'
              Action: 'kms:*'
              Resource: '*'
        Tags:
          - Key: Name
            Value: "AWS Summit 18 UG"
    MasterKeyAlias:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: alias/summit18
        TargetKeyId:
          Ref: MasterKey

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
